
package fr.ndaniel.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://ws.ndaniel.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimeServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsString", targetNamespace = "http://ws.ndaniel.fr/", className = "fr.ndaniel.client.GetTimeAsString")
    @ResponseWrapper(localName = "getTimeAsStringResponse", targetNamespace = "http://ws.ndaniel.fr/", className = "fr.ndaniel.client.GetTimeAsStringResponse")
    @Action(input = "http://ws.ndaniel.fr/TimeServer/getTimeAsStringRequest", output = "http://ws.ndaniel.fr/TimeServer/getTimeAsStringResponse")
    public String getTimeAsString();

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTimeAsLong", targetNamespace = "http://ws.ndaniel.fr/", className = "fr.ndaniel.client.GetTimeAsLong")
    @ResponseWrapper(localName = "getTimeAsLongResponse", targetNamespace = "http://ws.ndaniel.fr/", className = "fr.ndaniel.client.GetTimeAsLongResponse")
    @Action(input = "http://ws.ndaniel.fr/TimeServer/getTimeAsLongRequest", output = "http://ws.ndaniel.fr/TimeServer/getTimeAsLongResponse")
    public long getTimeAsLong();

}
