
package client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CatsServiceImplService", targetNamespace = "http://cats/", wsdlLocation = "http://localhost:9081/ws/cats?wsdl")
@HandlerChain(file="handlers\\handlers.xml")
public class CatsServiceImplService
    extends Service
{

    private final static URL CATSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CATSSERVICEIMPLSERVICE_QNAME = new QName("http://cats/", "CatsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9081/ws/cats?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CATSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CatsServiceImplService() {
        super(__getWsdlLocation(), CATSSERVICEIMPLSERVICE_QNAME);
    }

    public CatsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATSSERVICEIMPLSERVICE_QNAME, features);
    }

    public CatsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CATSSERVICEIMPLSERVICE_QNAME);
    }

    public CatsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATSSERVICEIMPLSERVICE_QNAME, features);
    }

    public CatsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CatsService
     */
    @WebEndpoint(name = "CatsServiceImplPort")
    public CatsService getCatsServiceImplPort() {
        return super.getPort(new QName("http://cats/", "CatsServiceImplPort"), CatsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatsService
     */
    @WebEndpoint(name = "CatsServiceImplPort")
    public CatsService getCatsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cats/", "CatsServiceImplPort"), CatsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CATSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CATSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
